import * as z from "zod";

export const patientSchema = z.object({
  noRegMrs: z.string().min(1, "No Reg MRS diperlukan"),
  noRm: z.string().min(1, "No. RM diperlukan"),
  paviliun: z.string().min(1, "Paviliun diperlukan"),
  kelas: z.string().min(1, "Kelas diperlukan"),
  nama: z.string().min(1, "Nama diperlukan"),
  alamat: z.string().min(1, "Alamat diperlukan"),
  kota: z.string().min(1, "Kota diperlukan"),
  provinsi: z.string().min(1, "Provinsi diperlukan"),
  noTelp: z.string().min(1, "No. Telp diperlukan"),
  asalPasien: z.string().min(1, "Asal Pasien diperlukan"),
  biaya: z.string().min(1, "Biaya diperlukan"),
  tanggalMasuk: z.string().min(1, "Tanggal masuk diperlukan"), // using string for form input
  tanggalKeluar: z.string().optional().nullable(),
  tanggalMeninggal: z.string().optional().nullable(),
  tanggalLahir: z.string().min(1, "Tanggal lahir diperlukan"),
  gender: z.string().min(1, "Gender diperlukan"),
  umur: z.string().min(1, "Umur diperlukan"),
  bangsa: z.string().min(1, "Bangsa diperlukan"),
  agama: z.string().min(1, "Agama diperlukan"),
  pendidikan: z.string().min(1, "Pendidikan diperlukan"),
  pekerjaan: z.string().min(1, "Pekerjaan diperlukan"),
  statusPernikahan: z.string().optional().nullable(),
  namaSuamiIstri: z.string().optional().nullable(),
  namaAyah: z.string().optional().nullable(),
  namaIbu: z.string().optional().nullable(),
  noRmIbu: z.string().optional().nullable(),
  pekerjaanIbu: z.string().optional().nullable(),
  asalMrs: z.string().min(1, "Asal MRS diperlukan"),
  dokter1: z.string().min(1, "Dokter I diperlukan"),
  dokter2: z.string().optional().nullable(),
  dokter3: z.string().optional().nullable(),
  dokter4: z.string().optional().nullable(),
  diagnosaMasuk: z.string().min(1, "Diagnosa Masuk diperlukan"),
  jenisKasus: z.string().min(1, "Jenis kasus diperlukan"),
  
  daruratNama: z.string().min(1, "Nama kontak darurat diperlukan"),
  daruratAlamat: z.string().min(1, "Alamat kontak darurat diperlukan"),
  daruratTelepon: z.string().min(1, "Telepon kontak darurat diperlukan"),
  daruratHubungan: z.string().min(1, "Hubungan kontak darurat diperlukan"),

  diagnosaKeluar: z.string().optional().nullable(),
  diagnosaUtama: z.string().optional().nullable(),
  diagnosaTambahan: z.string().optional().nullable(),
  diagnosaKomplikasi: z.string().optional().nullable(),
  penyebabTrauma: z.string().optional().nullable(),
  operasiTindakan1: z.string().optional().nullable(),
  operasiTindakan2: z.string().optional().nullable(),
  hasilPerawatan: z.string().optional().nullable(),
  caraKeluar: z.string().optional().nullable(),
});

export type PatientInput = z.infer<typeof patientSchema>;
